package:
  name: qutil
  version: 3.2.1

build:
  number: 6
  noarch: true

source:
  - url: https://github.com/nugend/qutil/archive/v3.2.1.tar.gz
    md5: 3fd181198bc02d4ffe9de812065389c1
    folder: src
  - path: ./
    folder: src

about:
  home: https://github.com/nugend/qutil
  license: MIT
  license_file: src/LICENSE
  summary: Q utilities by Dan Nugent, including package loading with version support

extra:
  author: Daniel Nugent
  author_email: nugend@gmail.com
