package:
  name: qspec
  version: 1.3.3

build:
  number: 4
  noarch: true

source:
  - url: https://github.com/nugend/qspec/archive/v1.3.3.tar.gz
    md5: 4bbda1a8806394da77f3ce76c88e8e25
  - path: ./

requirements:
  run:
    - qutil

about:
  home: https://github.com/nugend/qspec
  license: MIT
  license_file: ./LICENSE
  summary: Spec Testing Library for the Q Language by Dan Nugent

extra:
  author: Daniel Nugent
  author_email: nugend@gmail.com
